services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: istudios-container
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app:delegated"
      - "/usr/src/app/node_modules"
